cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false
    credentials:
      access-key: AKIAUTHAFHBXP5UGLDWG
      secret-key: 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
logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error
